apiVersion: loopstacks.io/v1
kind: Agent
metadata:
  name: intent-classifier
  namespace: default
spec:
  runtime:
    image: loopstacks/universal-runtime:latest
    language: typescript
    resources:
      cpu: "150m"
      memory: "256Mi"
  capabilities:
    - intent-classification
    - text-understanding
  schema:
    input:
      type: object
      properties:
        text:
          type: string
          description: "Text to classify for intent"
          maxLength: 5000
        context:
          type: object
          description: "Additional context for classification"
          properties:
            domain:
              type: string
              description: "Domain context (e.g., customer-service, e-commerce)"
            previousMessages:
              type: array
              items:
                type: string
              description: "Previous conversation messages for context"
      required:
        - text
    output:
      type: object
      properties:
        intent:
          type: string
          description: "Detected intent category"
        confidence:
          type: number
          minimum: 0
          maximum: 1
          description: "Confidence score from 0 to 1"
        entities:
          type: array
          items:
            type: object
            properties:
              type:
                type: string
              value:
                type: string
              confidence:
                type: number
          description: "Extracted entities from the text"
        suggestedActions:
          type: array
          items:
            type: string
          description: "Suggested next actions based on intent"
      required:
        - intent
        - confidence
  metadata:
    name: "Intent Classifier"
    description: "Classifies user intent from natural language text"
    version: "1.0.0"
    author: "LoopStacks Team"
    tags:
      - "nlp"
      - "intent"
      - "classification"
      - "conversation"