apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: agents.loopstacks.io
spec:
  group: loopstacks.io
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              runtime:
                type: object
                properties:
                  image:
                    type: string
                    description: "Container image for the agent runtime"
                  language:
                    type: string
                    enum: ["typescript", "python", "go"]
                    description: "Programming language for the agent"
                  resources:
                    type: object
                    properties:
                      cpu:
                        type: string
                        default: "100m"
                      memory:
                        type: string
                        default: "128Mi"
                required:
                - image
                - language
              capabilities:
                type: array
                items:
                  type: string
                description: "List of capabilities this agent provides"
              schema:
                type: object
                properties:
                  input:
                    type: object
                    description: "JSON schema for agent input"
                  output:
                    type: object
                    description: "JSON schema for agent output"
                required:
                - input
                - output
              metadata:
                type: object
                properties:
                  name:
                    type: string
                  description:
                    type: string
                  version:
                    type: string
                  author:
                    type: string
                  tags:
                    type: array
                    items:
                      type: string
            required:
            - runtime
            - capabilities
            - schema
          status:
            type: object
            properties:
              phase:
                type: string
                enum: ["Pending", "Ready", "Failed"]
                default: "Pending"
              message:
                type: string
              lastUpdated:
                type: string
                format: date-time
              instances:
                type: integer
                default: 0
    additionalPrinterColumns:
    - name: Language
      type: string
      jsonPath: .spec.runtime.language
    - name: Capabilities
      type: string
      jsonPath: .spec.capabilities
    - name: Status
      type: string
      jsonPath: .status.phase
    - name: Instances
      type: integer
      jsonPath: .status.instances
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
  scope: Namespaced
  names:
    plural: agents
    singular: agent
    kind: Agent
    shortNames:
    - ag