apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: agentinstances.loopstacks.io
spec:
  group: loopstacks.io
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              agent:
                type: string
                description: "Reference to the Agent resource"
              realm:
                type: string
                description: "Reference to the Realm resource"
              replicas:
                type: integer
                default: 1
                minimum: 0
                maximum: 100
                description: "Number of agent instances to run"
              resources:
                type: object
                properties:
                  cpu:
                    type: string
                    default: "100m"
                  memory:
                    type: string
                    default: "128Mi"
                  storage:
                    type: string
                    default: "1Gi"
              config:
                type: object
                description: "Agent-specific configuration"
                additionalProperties: true
              autoscaling:
                type: object
                properties:
                  enabled:
                    type: boolean
                    default: false
                  minReplicas:
                    type: integer
                    default: 1
                  maxReplicas:
                    type: integer
                    default: 10
                  targetCPUUtilization:
                    type: integer
                    default: 70
                  targetMemoryUtilization:
                    type: integer
                    default: 80
              placement:
                type: object
                properties:
                  nodeSelector:
                    type: object
                    additionalProperties:
                      type: string
                  tolerations:
                    type: array
                    items:
                      type: object
                  affinity:
                    type: object
            required:
            - agent
            - realm
          status:
            type: object
            properties:
              phase:
                type: string
                enum: ["Pending", "Running", "Scaling", "Failed", "Terminating"]
                default: "Pending"
              message:
                type: string
              lastUpdated:
                type: string
                format: date-time
              readyReplicas:
                type: integer
                default: 0
              currentReplicas:
                type: integer
                default: 0
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                    lastTransitionTime:
                      type: string
                      format: date-time
                    reason:
                      type: string
                    message:
                      type: string
    additionalPrinterColumns:
    - name: Agent
      type: string
      jsonPath: .spec.agent
    - name: Realm
      type: string
      jsonPath: .spec.realm
    - name: Replicas
      type: string
      jsonPath: .status.readyReplicas/.spec.replicas
    - name: Status
      type: string
      jsonPath: .status.phase
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
  scope: Namespaced
  names:
    plural: agentinstances
    singular: agentinstance
    kind: AgentInstance
    shortNames:
    - ai